dist: trusty
language: php
cache:
  directories:
  - node_modules
php:
- 5.4
- 5.5
- 5.6
- 7.0
- 7.1
matrix:
  include:
  - php: 5.2
    dist: precise
  - php: 5.3
    dist: precise
  - php: 7.2
  - php: 7.3
env:
  matrix:
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=4.9 WP_MULTISITE=0
  - WP_VERSION=4.8 WP_MULTISITE=0
  - WP_VERSION=4.7 WP_MULTISITE=0
  - WP_VERSION=4.6 WP_MULTISITE=0
  - WP_VERSION=4.5 WP_MULTISITE=0
  - WP_VERSION=4.4 WP_MULTISITE=0
  global:
  - WP_TRAVISCI=travis:phpunit
before_script:
- |
  # Remove Xdebug for a huge performance increase, but not from nightly or hhvm:
    stable='^[0-9\.]+$'
    if [[ "$TRAVIS_PHP_VERSION" =~ $stable ]]; then
      phpenv config-rm xdebug.ini
    fi
- |
  # Export Composer's global bin dir to PATH, but not on PHP 5.2:
  if [[ ${TRAVIS_PHP_VERSION:0:3} != "5.2" ]]; then
    composer config --list --global
    export PATH=`composer config --list --global | grep '\[home\]' | { read a; echo "${a#* }/vendor/bin:$PATH"; }`
  fi
- |
  # Install the specified version of PHPUnit depending on the PHP version:
  if [[ "$WP_TRAVISCI" == "travis:phpunit" ]]; then
    case "$TRAVIS_PHP_VERSION" in
      7.2|7.3)
        echo "Using PHPUnit 6.0"
        composer global require "phpunit/phpunit=6.0.*"
        ;;
      7.1|7.0|hhvm|nightly)
        echo "Using PHPUnit 5.7"
        composer global require "phpunit/phpunit=5.7.*"
        ;;
      5.6|5.5|5.4|5.3)
        echo "Using PHPUnit 4.8"
        composer global require "phpunit/phpunit=4.8.*"
        ;;
      5.2)
        # Do nothing, use default PHPUnit 3.6.x
        echo "Using default PHPUnit, hopefully 3.6"
        ;;
      *)
        echo "No PHPUnit version handling for PHP version $TRAVIS_PHP_VERSION"
        exit 1
        ;;
    esac
  fi
- npm --version
- node --version
- nvm install 6.9.1
- npm install -g grunt-cli
- npm install
- npm prune
- mysql --version
- phpenv versions
- php --version
- |
  # Debug PHP extensions, but not on HHVM because the command hangs indefinitely:
  if [[ "$TRAVIS_PHP_VERSION" != 'hhvm' ]]; then
    php -m
  fi
- npm --version
- node --version
- which phpunit
- phpunit --version
- curl --version
- grunt --version
- git --version
- svn --version
- git clone https://${GFTOKEN}@github.com/gravityforms/gravityforms.git $PWD/tmp/gravityforms
- git clone https://github.com/gravityflow/gravityflow.git $PWD/tmp/gravityflow
- bash tests/bin/install.sh wordpress_unit_tests root '' localhost $WP_VERSION
script: phpunit
notifications:
  slack:
    rooms:
      - secure: jDvKvgcIrx1UKrM/3Ny/TVHP9QQURBvQ4lTSBqbn871+TMzlrIAytbQjxD0DJ8nuqbHTybyOHhS4AzmeRjnlb2WGHVaJemWkkRzIv9/IfBLZ5OWcG5L1UpH6EaLw334ReVwnwo+FmEbxNtzv4Y1J6v1zFM4KacGKMoR7wtkehQuTMddXQY27zsE6QOaoHLXQ0WdfmcdhvuM43Ki4QgP07I5OPkGJIOOBD5CoeE7+NYmw+K9Z49I7UJ560s08y2K+/5bcpFHtmX84Fe9sSDiIEfEutmvYm1GnJ066MN7iXiogdnu5Src9hepOYcA6I31pw7pAbyDAhNk5cccjqBr5DU8xltNP5Ar34GD3qZWkxu2sPwBn2WLkviAJfsFdUYeTjNjzGF2rP5Q/Mjm87ZF/wMqduIKDCEWqYB7bufXBbPHEyWWltT2jTFnUvrdice9RPlwjDkjUTyq1dLZbEXpCRqfYwi53XvDIBcQk+Omhy4GbvWto5rOecaEDSovR+b2RYdDvmCAY2m6jc1winE/xNncx1mk62COoook+B7wJixVH+Ejk2OGVp+FIGLYNycAwwWSoR2jqIV35G9WKwMSwN2e9ol+SEE48Hu76x5m1YGSUrg2v+9SPtuooEzJLrLme98dp/XHRtkVdSE1wzGSoDnTGBfFvuVRXFYdwR4WihNM=
