dist: trusty
language: php
cache:
  directories:
  - node_modules
php:
  - 5.6
  - 7.0
  - 7.1
matrix:
  include:
    - php: 5.2
      dist: precise
      env: WP_VERSION=5.1 WP_MULTISITE=0
    - php: 5.3
      dist: precise
      env: WP_VERSION=5.1 WP_MULTISITE=0
    - php: 7.2
    - php: 7.3
env:
  matrix:
    - WP_VERSION=latest WP_MULTISITE=0
    - WP_VERSION=5.1 WP_MULTISITE=0
    - WP_VERSION=5.0 WP_MULTISITE=0
    - WP_VERSION=4.8 WP_MULTISITE=0
    - WP_VERSION=4.7 WP_MULTISITE=0
    - WP_VERSION=4.5 WP_MULTISITE=0
  global:
  - WP_TRAVISCI=travis:phpunit
before_script:
- |
  # Remove Xdebug for a huge performance increase, but not from nightly or hhvm:
    stable='^[0-9\.]+$'
    if [[ "$TRAVIS_PHP_VERSION" =~ $stable ]]; then
      phpenv config-rm xdebug.ini
    fi
- |
  # Export Composer's global bin dir to PATH, but not on PHP 5.2:
  if [[ ${TRAVIS_PHP_VERSION:0:3} != "5.2" ]]; then
    composer config --list --global
    export PATH=`composer config --list --global | grep '\[home\]' | { read a; echo "${a#* }/vendor/bin:$PATH"; }`
  fi
- |
  # Install the specified version of PHPUnit depending on the PHP version:
  if [[ "$WP_TRAVISCI" == "travis:phpunit" ]]; then
    case "$TRAVIS_PHP_VERSION" in
      7.2|7.3)
        echo "Using PHPUnit 6.0"
        composer global require "phpunit/phpunit=6.0.*"
        ;;
      7.1|7.0|hhvm|nightly)
        echo "Using PHPUnit 5.7"
        composer global require "phpunit/phpunit=5.7.*"
        ;;
      5.6|5.5|5.4|5.3)
        echo "Using PHPUnit 4.8"
        composer global require "phpunit/phpunit=4.8.*"
        ;;
      5.2)
        # Do nothing, use default PHPUnit 3.6.x
        echo "Using default PHPUnit, hopefully 3.6"
        ;;
      *)
        echo "No PHPUnit version handling for PHP version $TRAVIS_PHP_VERSION"
        exit 1
        ;;
    esac
  fi
- npm --version
- node --version
- nvm install 6.9.1
- npm install -g grunt-cli
- npm install
- npm prune
- mysql --version
- phpenv versions
- php --version
- |
  # Debug PHP extensions, but not on HHVM because the command hangs indefinitely:
  if [[ "$TRAVIS_PHP_VERSION" != 'hhvm' ]]; then
    php -m
  fi
- npm --version
- node --version
- which phpunit
- phpunit --version
- curl --version
- grunt --version
- git --version
- svn --version
- git clone https://${GFTOKEN}@github.com/gravityforms/gravityforms.git $PWD/tmp/gravityforms
- git clone https://github.com/gravityflow/gravityflow.git $PWD/tmp/gravityflow
- bash tests/bin/install.sh wordpress_unit_tests root '' localhost $WP_VERSION
script: phpunit
notifications:
  slack:
    secure: aog+yEHEsEAqOOgh50hPzRZl/2QjJcjzzpD1sQxDFo+RRrgTA/zX/Y0z0VdSqe316vcbzYnVLwNWf6l3xN/kNiCecJHxkm0/+nKxha1NL8TTwGcg9gv+GFoK47nZjU9aKSY6497v5cK0/wO5ohH2M61H/lf0oTEMXWklZngoEetW9jJa1jodSRhfONlvMbVQL5Em+m751ZYvLyJxRVVydYujUr/mKXxKwRGegFdU/kBDn6vqhpvflHG0eFa8d8hg4WZxxTpBQ95g/JDvDREygNyhR2M2ALywaW6O2AHxnOOAI4M1bL2xH4XdOBt7eC/hSWEPG7vm9a5j7/arRk7sLtEH44cV9uA0CqyeBPu8csmY9fof6UpZuchVp107//jKuOSdreFAgOvkB/bKE4TsU+FjbLDmHM5gFMZX+gRKJAeqoVB5zlRQJTU4lzFSURj67D+BlGbaQZMucDawdhn29UDnDcrT9OiD3JNllr4fTUGb2w8aSxnzmdQTvcjlC8tfGOy+GNgJLzpZ7MjndEIpBHcTM9p5jlhT0qk+tIaWsL4T69wwVrSiwnU9EqWlUwJrxBzKJ0YmeZt57x1nnQs6lH/Te5WHnP3BhruwM3eiYD/aMdXXgrtv1MTLVI/71Gi62JgEMZOq2kAy80bw4F7sdadiC+PSW+sGHjqEqeOROwA=
